[[tasks]]
task_id = "248fa5e0-a3ac-4de0-a077-307c80d12126"
question = "What's 9 + 10?"
    [[tasks.public_test_cases]]
    stdin = "9,10"
    expected = "19"
    [[tasks.private_test_cases]]
    stdin = "9,10"
    expected = "19"
    [[tasks]]
task_id = "248fa5e0-a3ac-4de0-a077-307c80d12126"
question = "What's 9 + 10?"
    [[tasks.public_test_cases]]
    stdin = "9,10"
    expected = "19"
    [[tasks.private_test_cases]]
    stdin = "9,10"
    expected = "19"
[[tasks]]
task_id = "248fa5e0-a3ac-4de0-a077-307c80d12126"
question = "What's 9 + 10?"
    [[tasks.public_test_cases]]
    stdin = "9,10"
    expected = "19"
    [[tasks.private_test_cases]]
    stdin = "9,10"
    expected = "19"